### ISSUE TITLE
Please tell me the port numbers GPIO on Raspberry

### ISSUE THREAD

**Issue by pavellyba** [michal037/driver-ST7735S#1]
I'm don't understand your tutorial=(
Please tell me the port numbers GPIO to connect port on display.

In LCD port
1 | VCC |
2 | GND | 
3 | CS | 
4 | RESET | 
5 | A0 |
6 | SDA | 
7 | SCK | 
8 | LED | 

On GPIO port -Where is it?

**Comment by michal037** [comment]
In the RaspberryPi configuration, activate the hardware SPI module.
You can use the instructions on the official website.

Type as root `gpio readall` in bash.
You will see a list of physical pins with a description. 
For example: physical pin numer 19 is identified with pin numer 12 in WiringPi library. 
In my library you must use the pin number from WiringPi.

Connect VCC from display header to any VCC pin from RaspberryPi header.
LED pin connect to VCC. 
GND to GND. 
CS from display to 'CE0' or 'CE1' from WiringPi table. 
SCK, SDA to RaspberryPi SPI physical interface. 
A0 and RESET to any GPIO from header then you must enter their WiringPi numbers in the function that initializes the display.

**Comment by pavellyba** [comment]
LED  is pin 01
VCC is pin 17
GND is pin 06
CS  is pin 24
A0 is pin 16
RESET is pin 18

SCK, SDA - Where is it?
```
//static st7735sType createDisplay(int SPISpeed, int cs, int a0, int rs);
st7735s.conf.createDisplay(15000000, 0, 23, 24);
```
This code correct?

![img](https://user-images.githubusercontent.com/34129685/35702948-916efcfc-07ab-11e8-88a4-fe1d5a98b4f9.jpg)

**Comment by michal037** [comment]
It seems to me that the code is correct.
SCK is SPI_CLK (23 physical).
SDA is SPI_MOSI (19 physical).

**Comment by michal037** [comment]
@pavellyba
Is everything solved and can I close the issue?

**Comment by pavellyba** [comment]
**I'm trying compiling source code from /driver-ST7735S/source/raspberrypi/**
_change in main.c:_
`st7735s.conf.createDisplay(15000000, 0, 23, 24);`

_run command_
`gcc -lwiringPi main.c -o test`

_error:_
```
In function 'main':
undefined reference to 'st7735s'
```

What need writing?
sorry, I'm noob=)

**Comment by pavellyba** [comment]
Run command:
`gcc -lwiringPi main.c st7735s.c -o test`

and in my code error:
`st7735sType disp1 = st7735s.conf.createDisplay(15000000, 0, **4**, **5**)`

THIS WORK! Thank you! You are a genius!
Now I'm waiting for the tutorial - Fast drawing =)
https://github.com/michal037/driver-ST7735S/blob/master/documentation/core/fast-drawing.md

**Comment by michal037** [comment]
try this: `gcc -lwiringpi st7735s.h st7735s.c main.c -o test`

**Comment by pavellyba** [comment]
Thanks, I already figured it out. THIS WORK! Thank you! You are a genius!

Now I'm waiting for the tutorial - Fast drawing =)
https://github.com/michal037/driver-ST7735S/blob/master/documentation/core/fast-drawing.md
