### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by thaker123** [michal037/driver-ST7735S#2]
this code is not working for tft 128*120 please guide me.
thanks

**Comment by michal037** [comment]
Because the library has a manually entered resolution of 128x160.
This can be changed very easily.
Just *Fork* this repository and let me know here, I will send you patches that should help you.

**Comment by thaker123** [comment]
@michal037 sir i already done this in driver-st7735s.c ,but there is no effect was found.

**Comment by thaker123** [comment]
the connection is according to wiring pi 
5v - vdd
scl - sclk 
sda - mosi
cs - ce0
rst - gpio 3
dc - gpio 5

**Comment by michal037** [comment]
Change the resolution in **main.c** too and this line:
`myDisplay = lcdst_init(30000000, 0, 9, 8);` to `myDisplay = lcdst_init(30000, 0, 9, 8);`. Maybe SPI Speed ​​is too high?

Anything appearing on the screen?  Is it blank?  Does your driver have an 'S' ending?
There are a lot of sub types of these displays on the market, I don't have all of them, I have no way to check the code for them.
