### ISSUE TITLE
Raspberry Pi Spidev1.0

### ISSUE THREAD

**Issue by gerry210** [michal037/driver-ST7735S#4]
Hello michal037, 

thanks a lot for your work, but I have one question: 

It is possible to use your code on the raspberry Pi for the spidev1.0? 

best regards 
gerry210

**Comment by michal037** [comment]
Hi @gerry210 

WiringPi doesn't support SPI other than `spidev0.x`. You must create your own library for SPI support and then replace WiringPi functions in my code (`st7735s.c`, `main.c`). Check [gpio structure](https://github.com/michal037/driver-ST7735S/blob/50946c7fcdb9fa4223743987852903df4b5a85e4/source/st7735s.c#L28), replace the function pointers in it.


Here you can see what the SPI code from WiringPi looked like:
[wiringPiSPI.c](https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPiSPI.c)

The author doesn't currently provide the source code:
[wiringPi – deprecated…](http://wiringpi.com/wiringpi-deprecated)
[WiringPi source code](https://git.drogon.net)
